### ISSUE TITLE
[BUG] Module import failed for Naming Series (erpnext.setup.doctype.naming_series.naming_series Error: cannot import name 'validate_series' 

### ISSUE THREAD

**Issue by daemex** [Monogramm/docker-erpnext#47]
**Describe the bug**

Hi there, upon starting the container (debian, alpine, or slim), the build is successful but when the container is started, ERPNext fails to install with the following error: Module import failed for Naming Series (erpnext.setup.doctype.naming_series.naming_series Error: cannot import name 'validate_series' from 'frappe.core.doctype.doctype.doctype' (/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py

**To Reproduce**
1. Build any of the images and set all .env
2. sudo docker-compose up --force-recreate
3. The error shows in the logs when attempting to install ERPNext
4. When logged into Frappe web interface and click About, ERPNext is not installed, only the frappe framework.

Provide Docker commands or docker-compose file if possible.

```
version: "2.3"

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
#  sut:
#    build:
#      context: ./test
#      dockerfile: Dockerfile
#    command: sh /docker_test.sh
#    # Only for travis-ci, do not name test container in dockerhub
#    container_name: sut
#    depends_on:
#      - erpnext_db
#      - erpnext_app
#      - erpnext_web
#      - erpnext_scheduler
#      - erpnext_worker_default
#      - erpnext_worker_long
#      - erpnext_worker_short
#      - erpnext_socketio
#      - erpnext_redis_cache
#      - erpnext_redis_queue
#      - erpnext_redis_socketio
#    environment:
#      # Container setup
#      - NODE_TYPE=sut
#      # Docker setup
#      - DOCKER_APPS_TIMEOUT=900
#      - DOCKER_DEBUG=1
#    volumes_from:
#      - erpnext_app
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro

  erpnext_app:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm/docker-erpnext:13-alpine
    container_name: erpnext_app
    command: app
    #restart: always
    ports:
      - 8551:8000
    depends_on:
      - erpnext_db
    links:
      - erpnext_db
    environment:
      # Docker setup
      - DOCKER_DB_ALLOWED_HOSTS=
      - DOCKER_GUNICORN_TIMEOUT=600
      # Frappe setup
      - FRAPPE_APP_INIT=erpnext
      - FRAPPE_APP_RESET=1
      - FRAPPE_DEFAULT_PROTOCOL=https://
      - FRAPPE_DEFAULT_SITE=${ERPNEXT_SITE}
      - FRAPPE_SOCKETIO_PORT=3000
      - FRAPPE_LOGGING=1
      - DEVELOPER_MODE=0
      - ALLOW_TESTS=1
      #- ADMIN_USER=Administrator
      - ADMIN_PASSWORD=${ERPNEXT_ADMIN_PWD}
      - ENCRYPTION_KEY=${ERPNEXT_ENCRYPTION_KEY}
      # Database setup
      - DB_TYPE=mariadb
      - DB_HOST=erpnext_db
      - DB_PORT=3306
      - DB_NAME=${ERPNEXT_DB_NAME}
      - DB_PASSWORD=${ERPNEXT_DB_PWD}
      - DB_ROOT_PASSWORD=${ERPNEXT_DB_ROOT_PWD}
      # Mail setup
      - MAIL_HOST=${ERPNEXT_MAIL_HOST}
      - MAIL_PORT=587
      - MAIL_USE_SSL=tls
      - MAIL_LOGIN=${ERPNEXT_SMTP_USER}
      - MAIL_PASSWORD=${ERPNEXT_SMTP_PWD}
      # Redis setup
      - REDIS_CACHE_HOST=erpnext_redis_cache
      - REDIS_QUEUE_HOST=erpnext_redis_queue
      - REDIS_SOCKETIO_HOST=erpnext_redis_socketio
    volumes:
      - ./erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - .//erpnext/frappe/logs:/home/frappe/frappe-bench/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_web:
    image: nginx:alpine
    container_name: erpnext_web
    #restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    volumes_from:
      - erpnext_app
    ports:
      - 8552:80
      # If you need SSL connection
      # - '443:443'
    links:
      - erpnext_app
      - erpnext_socketio

  erpnext_db:
    image: mariadb:10
    container_name: erpnext_db
    #restart: always
    command: --character_set_client=utf8 --bind-address=0.0.0.0 --character-set-client-handshake=FALSE --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="ALLOW_INVALID_DATES"
    environment:
      - MYSQL_ROOT_PASSWORD=${ERPNEXT_DB_ROOT_PWD}
      # Following parameters are not needed with Frappe 12 or higher since it will create DB itself
      - MYSQL_DATABASE=${ERPNEXT_DB_NAME}
      - MYSQL_USER=${ERPNEXT_DB_NAME}
      - MYSQL_PASSWORD=${ERPNEXT_DB_PWD}
    volumes:
      - ./erpnext/db:/var/lib/mysql

  erpnext_scheduler:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm/docker-erpnext:13-alpine
    container_name: erpnext_scheduler
    command: scheduler
    #restart: always
    depends_on:
      - erpnext_app
    volumes_from:
      - erpnext_app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_worker_default:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm/docker-erpnext:13-alpine
    container_name: erpnext_worker_default
    command: worker-default
    #restart: always
    depends_on:
      - erpnext_app
    environment:
      # Docker setup
      - DOCKER_APPS_TIMEOUT=900
    volumes_from:
      - erpnext_app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_worker_long:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm/docker-erpnext:13-alpine
    container_name: erpnext_worker_long
    command: worker-long
    #restart: always
    depends_on:
      - erpnext_app
    environment:
      # Docker setup
      - DOCKER_APPS_TIMEOUT=900
    volumes_from:
      - erpnext_app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_worker_short:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm/docker-erpnext:13-alpine
    container_name: erpnext_worker_short
    command: worker-short
    #restart: always
    depends_on:
      - erpnext_app
    environment:
      # Docker setup
      - DOCKER_APPS_TIMEOUT=900
    volumes_from:
      - erpnext_app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_socketio:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm/docker-erpnext:13-alpine
    container_name: erpnext_socketio
    command: node-socketio
    #restart: always
    ports:
      - 3000:3000
    depends_on:
      - erpnext_app
    environment:
      # Docker setup
      - DOCKER_APPS_TIMEOUT=900
    volumes_from:
      - erpnext_app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_redis_cache:
    image: redis:alpine
    container_name: erpnext_redis_cache
    command: ["redis-server","/etc/conf.d/redis.conf"]
    #restart: always
    volumes:
      - ./services/erpnext/conf/redis_cache.conf:/etc/conf.d/redis.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_redis_queue:
    image: redis:alpine
    container_name: erpnext_redis_queue
    #restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_redis_socketio:
    image: redis:alpine
    container_name: erpnext_redis_socketio
    #restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```

**Expected behavior**

ERPNext and Frappe framework are both installed without the import failed issue.

**Screenshots**

**Stack trace**
If applicable, add stack trace using `docker logs` or `docker-compose logs` to identify the problem.

erpnext_app               | Module import failed for Naming Series (erpnext.setup.doctype.naming_series.naming_series Error: cannot import name 'validate_series' from 'frappe.core.doctype.doctype.doctype' (/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py))
erpnext_app               | ✔ Built js/data_import_tools.min.js
erpnext_app               | Error: File to import not found or unreadable: frappe/public/scss/common/mixins.
erpnext_app               | UNRESOLVED_IMPORT : 'onscan.js' is imported by ../erpnext/erpnext/selling/page/point_of_sale/pos_item_selector.js, but could not be resolved – treating it as an external dependency

**Docker (please complete the following information):**

-   Docker / Docker-compose Version: (e.g. Docker version 18.03.0-ce, build 0520e24)
-   Image (e.g. 7.0-apache)

Docker version = Docker version 20.10.2, build 2291f61
Docker Compose version = 1.27.4, build 40524192

**Desktop (please complete the following information):**

-   OS: (e.g. iOS)
-   Browser (e.g. chrome, safari)
-   Version (e.g. 22)

**Smartphone (please complete the following information):**

-   Device: (e.g. iPhone6)
-   OS: (e.g. iOS8.1)
-   Browser (e.g. stock browser, safari)
-   Version (e.g. 22)

**Additional context**

**Comment by ziedbouf** [comment]
Hi Everyone, same in here several error related the module installation
```
     | Installing erpnext_autoinstall...
erpnext_app               | An error occurred while installing erpnext_autoinstall:
erpnext_app               | Module import failed for Naming Series (erpnext.setup.doctype.naming_series.naming_series Error: cannot import name 'validate_series' from 'frappe.core.doctype.doctype.doctype' (/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py))
erpnext_app               | Exception ignored in: <function Connection.__del__ at 0x7fe61a2d57a0>
erpnext_app               | Traceback (most recent call last):
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/redis/connection.py", line 537, in __del__
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/redis/connection.py", line 664, in disconnect
erpnext_app               | TypeError: 'NoneType' object is not callable
erpnext_worker_long       | 16:17:26 Worker rq:worker:da1463f942804ae080fd07928472f976.4395eb58a7d8.55.long: started, version 1.6.1
erpnext_worker_long       | 16:17:26 Subscribing to channel rq:pubsub:da1463f942804ae080fd07928472f976.4395eb58a7d8.55.long
erpnext_worker_long       | 16:17:26 *** Listening on long...
erpnext_app               | [app] [2021-11-15T16:17:26+01:00] Adding 'erpnext_ocr' to apps.txt...
erpnext_app               | [app] [2021-11-15T16:17:26+01:00] Installing app 'erpnext_ocr'...
erpnext_db                | 2021-11-15 16:17:30.244 CET [32] WARNING:  there is no transaction in progress
erpnext_app               | 
erpnext_app               | Installing erpnext_ocr...
erpnext_db                | 2021-11-15 16:17:30.301 CET [32] WARNING:  there is no transaction in progress
erpnext_db                | 2021-11-15 16:17:30.322 CET [32] WARNING:  there is no transaction in progress
erpnext_db                | 2021-11-15 16:17:30.654 CET [32] WARNING:  there is no transaction in progress
erpnext_db                | 2021-11-15 16:17:30.679 CET [32] WARNING:  there is no transaction in progress
erpnext_db                | 2021-11-15 16:17:30.740 CET [32] WARNING:  there is no transaction in progress
erpnext_db                | 2021-11-15 16:17:30.759 CET [32] WARNING:  there is no transaction in progress
erpnext_db                | 2021-11-15 16:17:30.845 CET [32] WARNING:  there is no transaction in progress
erpnext_db                | 2021-11-15 16:17:30.862 CET [32] WARNING:  there is no transaction in progress
erpnext_db                | 2021-11-15 16:17:30.933 CET [32] WARNING:  there is no transaction in progress
Updating DocTypes for erpnext_ocr   : [========================================] 100%
erpnext_app               | An error occurred while installing erpnext_ocr:
erpnext_app               | Module import failed for Naming Series (erpnext.setup.doctype.naming_series.naming_series Error: cannot import name 'validate_series' from 'frappe.core.doctype.doctype.doctype' (/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py))
erpnext_app               | Exception ignored in: <function Connection.__del__ at 0x7fa8fa1447a0>
erpnext_app               | Traceback (most recent call last):
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/redis/connection.py", line 537, in __del__
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/redis/connection.py", line 664, in disconnect
erpnext_app               | TypeError: 'NoneType' object is not callable
erpnext_app               | [app] [2021-11-15T16:17:31+01:00] Adding 'recod_erpnext_design' to apps.txt...
erpnext_app               | [app] [2021-11-15T16:17:31+01:00] Installing app 'recod_erpnext_design'...
erpnext_db                | 2021-11-15 16:17:34.264 CET [33] WARNING:  there is no transaction in progress
erpnext_app               | 
erpnext_app               | Installing recod_erpnext_design...
erpnext_app               | An error occurred while installing recod_erpnext_design:
erpnext_app               | Module import failed for Naming Series (erpnext.setup.doctype.naming_series.naming_series Error: cannot import name 'validate_series' from 'frappe.core.doctype.doctype.doctype' (/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py))
erpnext_app               | Exception ignored in: <function Connection.__del__ at 0x7f19e88687a0>
erpnext_app               | Traceback (most recent call last):
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/redis/connection.py", line 537, in __del__
erpnext_app               |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/redis/connection.py", line 664, in disconnect
erpnext_app               | TypeError: 'NoneType' object is not callable
erpnext_app               | [app] [2021-11-15T16:17:34+01:00] Adding 'frappe_pwa' to apps.txt...
erpnext_app               | [app] [2021-11-15T16:17:34+01:00] Installing app 'frappe_pwa'...
erpnext_db                | 2021-11-15 16:17:37.628 CET [35] WARNING:  there is no transaction in progress
erpnext_db                | 2021-11-15 16:17:37.649 CET [35] WARNING:  there is no transaction in progress
erpnext_app               | 

```
